<?php
/**
 * Implementation of hook_elements().
 */
function smart_dates_elements() {
  return array(
    'date_popup' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#process' => array('smart_dates_process')
    ),
    'date' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#process' => array('smart_dates_process')
    )
  );
}

function smart_dates_process($element, $edit, $form_state, $form) {
  if ($element["#title"] == "From date") {
    drupal_add_js(drupal_get_path('module', 'smart_dates') . "/smart_dates.js");

    $date1 = '#' . $element["date"]["#id"];
    $date2 = str_replace("value", "value2", $date1);
    $time1 = '#' . $element["time"]["#id"];
    $time2 = str_replace("value", "value2", $time1);

    drupal_add_js("Drupal.behaviors.smart_dates = function() {
        DateAutoset.register_dates($('" . $date1 . "'), $('" . $date2 . "'));
        DateAutoset.register_times($('" . $time1 . "'), $('" . $time2 . "'));
     };", "inline");
  }
  return $element;
}

function theme_smart_dates($element) {
  return $element['#children'];
}
